from pathlib import Path

p = Path("main.py")
s = p.read_text(encoding="utf-8")

MARK = "# === INFINI_CORE_SHOP_RENDER_V1 ==="

if MARK in s:
    print("มี INFINI_CORE_SHOP_RENDER_V1 แล้ว ไม่เขียนซ้ำ")
else:
    helper = r'''

# === INFINI_CORE_SHOP_RENDER_V1 ===
# ทำให้ห้องความสามารถเอารูปสินค้าไปวางบนฉากจริง แล้วสร้างภาพผลลัพธ์ใหม่

def _core_file_path_from_url(url):
    try:
        name = str(url or "").split("/")[-1].split("?")[0]
        safe = _CorePath(name).name
        path = _CORE_UPLOADS / safe
        if path.exists():
            return path
    except Exception:
        pass
    return None


def _core_fit_cover_img(img, size):
    from PIL import Image
    img = img.convert("RGB")
    w, h = img.size
    tw, th = size
    scale = max(tw / w, th / h)
    nw, nh = int(w * scale), int(h * scale)
    img = img.resize((nw, nh), Image.LANCZOS)
    x = max(0, (nw - tw) // 2)
    y = max(0, (nh - th) // 2)
    return img.crop((x, y, x + tw, y + th))


def _core_fit_contain_img(img, size):
    from PIL import Image
    img = img.convert("RGBA")
    w, h = img.size
    tw, th = size
    scale = min(tw / w, th / h)
    nw, nh = int(w * scale), int(h * scale)
    return img.resize((nw, nh), Image.LANCZOS)


def _core_simple_cutout(img):
    """
    ตัดพื้นหลังขาว/สว่างแบบง่ายก่อน
    เหมาะกับรูปสินค้า background ขาว
    """
    from PIL import Image
    img = img.convert("RGBA")
    px = img.load()
    w, h = img.size

    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            # ตัดพื้นขาว/เทาอ่อน
            if r > 225 and g > 225 and b > 225:
                px[x, y] = (255, 255, 255, 0)
            elif r > 238 and g > 238 and b > 230:
                px[x, y] = (255, 255, 255, 0)

    return img


def _core_render_shop_scene(product_file=None, selected_scene=None, pattern="basic", goal="", extra_note=""):
    try:
        from PIL import Image, ImageDraw, ImageFont, ImageFilter
    except Exception:
        return None

    product_path = _core_file_path_from_url((product_file or {}).get("url"))
    scene_path = _core_file_path_from_url((selected_scene or {}).get("url"))

    if not product_path:
        return None

    W, H = 900, 1300

    # ฉาก
    if scene_path:
        bg = Image.open(scene_path)
        canvas = _core_fit_cover_img(bg, (W, H)).convert("RGBA")
    else:
        canvas = Image.new("RGBA", (W, H), (18, 10, 6, 255))

    draw = ImageDraw.Draw(canvas, "RGBA")

    # ดึงฉากให้มืดลงนิด เพื่อให้สินค้าเด่น
    canvas.alpha_composite(Image.new("RGBA", (W, H), (0, 0, 0, 80)))

    # กรอบแผ่น
    draw.rounded_rectangle((28, 28, W - 28, H - 28), radius=46, outline=(255, 154, 42, 180), width=4)

    try:
        font_big = ImageFont.truetype("DejaVuSans-Bold.ttf", 62)
        font_mid = ImageFont.truetype("DejaVuSans-Bold.ttf", 34)
        font_small = ImageFont.truetype("DejaVuSans.ttf", 25)
    except Exception:
        font_big = font_mid = font_small = None

    # Header
    draw.rounded_rectangle((58, 58, W - 58, 200), radius=30, fill=(0, 0, 0, 145), outline=(255, 154, 42, 120), width=2)
    draw.text((88, 82), "GOODRICH", fill=(255, 255, 255, 255), font=font_big)
    draw.text((92, 150), str(pattern or "basic").upper() + " / AI SHOP SHEET", fill=(255, 183, 88, 255), font=font_small)

    # สินค้า
    prod = Image.open(product_path).convert("RGBA")
    prod = _core_simple_cutout(prod)
    prod = _core_fit_contain_img(prod, (620, 620))

    px = (W - prod.size[0]) // 2
    py = 330 + (620 - prod.size[1]) // 2

    # เงาใต้สินค้า
    alpha = prod.getchannel("A")
    shadow = Image.new("RGBA", prod.size, (0, 0, 0, 0))
    shadow.putalpha(alpha)
    shadow = shadow.filter(ImageFilter.GaussianBlur(24))
    canvas.alpha_composite(shadow, (px + 22, py + 34))
    canvas.alpha_composite(prod, (px, py))

    # กล่องข้อมูลล่าง
    draw.rounded_rectangle((70, 980, W - 70, 1185), radius=34, fill=(18, 8, 3, 220), outline=(255, 154, 42, 150), width=3)
    draw.text((105, 1015), "สินค้าอัปโหลดรอบนี้", fill=(255, 220, 188, 255), font=font_mid)

    short_goal = (goal or "พร้อมขาย").strip()
    if len(short_goal) > 34:
        short_goal = short_goal[:34] + "..."
    draw.text((105, 1070), short_goal, fill=(235, 220, 205, 240), font=font_small)

    draw.rounded_rectangle((595, 1040, 785, 1138), radius=26, fill=(255, 154, 42, 235))
    draw.text((635, 1060), "SALE", fill=(20, 10, 5, 255), font=font_mid)

    draw.text((92, 1225), "Generated by INFINI Core Ability", fill=(255, 183, 88, 220), font=font_small)

    name = "core_render_" + _CoreUuid.uuid4().hex + ".png"
    out = _CORE_UPLOADS / name
    canvas.convert("RGB").save(out, "PNG")

    return {
        "name": name,
        "url": "/ai-core-file/" + name,
        "kind": "rendered_shop_sheet"
    }

# === END INFINI_CORE_SHOP_RENDER_V1 ===
'''

    # ใส่ helper ก่อน ai-core-json หรือท้ายไฟล์
    target = '@app.get("/ai-core-json")'
    if target in s:
        s = s.replace(target, helper + "\n" + target, 1)
    else:
        s += helper

    # เพิ่ม rendered_file ในหน้าแสดงผล
    s = s.replace(
        'selected_scene = last.get("selected_scene")',
        'selected_scene = last.get("selected_scene")\n    rendered_file = last.get("rendered_file")',
        1
    )

    s = s.replace(
        'knowledge_img_html = ""',
        '''rendered_html = ""
    if rendered_file and rendered_file.get("url"):
        rendered_html = '<div class="preview-card"><h3>ผลลัพธ์จัดร้าน</h3><img src="' + _core_esc(rendered_file.get("url")) + '"><p class="small">ภาพที่ระบบจัดจากสินค้า + ฉาก</p></div>'

    knowledge_img_html = ""''',
        1
    )

    s = s.replace(
        "(product_html + scene_html or '<p class=\"muted\">ยังไม่มีรูปที่ใช้ล่าสุด</p>')",
        "(rendered_html + product_html + scene_html or '<p class=\"muted\">ยังไม่มีรูปที่ใช้ล่าสุด</p>')",
        1
    )

    # เพิ่ม render ตอนกด build
    old = '''    result, images, selected_scene = _core_build_output(
        goal=goal,
        pattern=pattern,
        extra_note=extra_note,
        product_file=product_file,
        scene_file=scene_file,
        scene_mode=scene_mode,
    )'''

    new = '''    result, images, selected_scene = _core_build_output(
        goal=goal,
        pattern=pattern,
        extra_note=extra_note,
        product_file=product_file,
        scene_file=scene_file,
        scene_mode=scene_mode,
    )

    rendered_file = _core_render_shop_scene(
        product_file=product_file,
        selected_scene=selected_scene,
        pattern=pattern,
        goal=goal,
        extra_note=extra_note,
    )

    if rendered_file:
        result += "\\n\\nสร้างภาพจัดร้านแล้ว: " + rendered_file.get("url", "")'''

    if old in s:
        s = s.replace(old, new, 1)
    else:
        print("เตือน: ไม่เจอบล็อก _core_build_output เดิม")

    s = s.replace(
        '''        "selected_scene": selected_scene,
        "result": result,''',
        '''        "selected_scene": selected_scene,
        "rendered_file": rendered_file,
        "result": result,''',
        1
    )

    p.write_text(s, encoding="utf-8")
    print("เพิ่ม INFINI_CORE_SHOP_RENDER_V1 แล้ว")

