from pathlib import Path

p = Path("main.py")
s = p.read_text(encoding="utf-8")

MARK = "# === AI_ABILITY_OFFLINE_RENDERER_V1 ==="

if MARK in s:
    print("มี AI_ABILITY_OFFLINE_RENDERER_V1 แล้ว ไม่เขียนซ้ำ")
else:
    helper = r'''

# === AI_ABILITY_OFFLINE_RENDERER_V1 ===
# สร้างภาพจัดแผ่นจริงแบบออฟไลน์จากรูปฉาก + รูปสินค้า
def _ab_url_to_path(url):
    try:
        name = str(url or "").split("/")[-1].split("?")[0]
        name = _ABPath(name).name
        path = _AB_UPLOADS / name
        if path.exists():
            return path
    except Exception:
        pass
    return None

def _ab_fit_cover(img, size):
    from PIL import Image
    img = img.convert("RGB")
    w, h = img.size
    tw, th = size
    scale = max(tw / w, th / h)
    nw, nh = int(w * scale), int(h * scale)
    img = img.resize((nw, nh), Image.LANCZOS)
    left = max(0, (nw - tw) // 2)
    top = max(0, (nh - th) // 2)
    return img.crop((left, top, left + tw, top + th))

def _ab_fit_contain(img, size):
    from PIL import Image
    img = img.convert("RGBA")
    w, h = img.size
    tw, th = size
    scale = min(tw / w, th / h)
    nw, nh = int(w * scale), int(h * scale)
    return img.resize((nw, nh), Image.LANCZOS)

def _ab_rounded_mask(size, radius):
    from PIL import Image, ImageDraw
    mask = Image.new("L", size, 0)
    d = ImageDraw.Draw(mask)
    d.rounded_rectangle((0, 0, size[0]-1, size[1]-1), radius=radius, fill=255)
    return mask

def _ab_render_ability_sheet(scene_file=None, product_file=None, pattern="basic", title="GOODRICH", color="orange"):
    try:
        from PIL import Image, ImageDraw, ImageFont, ImageFilter
    except Exception:
        return None

    scene_path = _ab_url_to_path(scene_file.get("url") if scene_file else "")
    product_path = _ab_url_to_path(product_file.get("url") if product_file else "")

    if not scene_path and not product_path:
        return None

    W, H = 900, 1300

    # พื้นหลัง
    if scene_path:
        bg = Image.open(scene_path)
        canvas = _ab_fit_cover(bg, (W, H))
    else:
        canvas = Image.new("RGB", (W, H), (18, 10, 6))

    canvas = canvas.convert("RGBA")
    draw = ImageDraw.Draw(canvas, "RGBA")

    # ทำให้ฉากดูเป็นแผ่นขาย ไม่ใช่รูปดิบ
    dark = Image.new("RGBA", (W, H), (0, 0, 0, 72))
    canvas.alpha_composite(dark)

    # กรอบนอก
    draw.rounded_rectangle((28, 28, W-28, H-28), radius=44, outline=(255, 156, 40, 180), width=4)

    # แถบบน
    draw.rounded_rectangle((55, 55, W-55, 210), radius=30, fill=(0, 0, 0, 145), outline=(255, 156, 40, 120), width=2)

    try:
        font_big = ImageFont.truetype("DejaVuSans-Bold.ttf", 58)
        font_mid = ImageFont.truetype("DejaVuSans-Bold.ttf", 34)
        font_small = ImageFont.truetype("DejaVuSans.ttf", 26)
    except Exception:
        font_big = font_mid = font_small = None

    draw.text((85, 78), "GOODRICH", fill=(255, 255, 255, 255), font=font_big)
    draw.text((88, 148), f"{str(pattern or 'basic').upper()} SHEET", fill=(255, 176, 75, 255), font=font_small)

    # ช่องสินค้า
    product_box = (90, 330, W-90, 900)
    draw.rounded_rectangle(product_box, radius=38, fill=(0, 0, 0, 120), outline=(255, 156, 40, 120), width=3)

    if product_path:
        prod = Image.open(product_path).convert("RGBA")
        prod = _ab_fit_contain(prod, (620, 520))

        # ใส่เงา
        shadow = Image.new("RGBA", prod.size, (0,0,0,0))
        alpha = prod.getchannel("A")
        shadow.putalpha(alpha)
        shadow = shadow.filter(ImageFilter.GaussianBlur(18))

        px = (W - prod.size[0]) // 2
        py = 365 + (520 - prod.size[1]) // 2

        canvas.alpha_composite(shadow, (px + 18, py + 24))
        canvas.alpha_composite(prod, (px, py))
    else:
        draw.text((160, 560), "NO PRODUCT IMAGE", fill=(255, 255, 255, 180), font=font_mid)

    # กล่องข้อมูลล่าง
    info_box = (70, 945, W-70, 1195)
    draw.rounded_rectangle(info_box, radius=34, fill=(18, 8, 3, 210), outline=(255, 156, 40, 150), width=3)

    draw.text((105, 980), "สินค้า / Product", fill=(255, 214, 170, 255), font=font_mid)
    draw.text((105, 1040), "พร้อมจัดลงแผ่นขาย", fill=(255, 255, 255, 230), font=font_small)
    draw.text((105, 1090), "ใช้ฉาก + สินค้าจริงที่อัปโหลด", fill=(210, 190, 170, 230), font=font_small)

    # ราคา mock เพื่อให้เห็น layout
    draw.rounded_rectangle((560, 1020, 785, 1125), radius=28, fill=(255, 156, 40, 230))
    draw.text((608, 1047), "3500", fill=(20, 10, 5, 255), font=font_big)

    # ป้ายล่าง
    draw.text((92, 1220), "Generated by INFINI Ability Room", fill=(255, 176, 75, 210), font=font_small)

    name = f"render_{_ABUuid.uuid4().hex}.png"
    out = _AB_UPLOADS / name
    canvas.convert("RGB").save(out, "PNG")

    return {
        "name": name,
        "url": f"/ai-ability-room/file/{name}",
        "kind": "rendered_sheet"
    }

# === END AI_ABILITY_OFFLINE_RENDERER_V1 ===
'''
    # วาง helper หลังฟังก์ชันเซฟ upload
    target = '@app.get("/ai-ability-room/file/{name}")'
    if target in s:
        s = s.replace(target, helper + "\n" + target, 1)
    else:
        s += helper

    old = '''    result = result + preview_html'''
    new = '''    rendered_sheet = _ab_render_ability_sheet(
        scene_file=scene_file,
        product_file=product_file,
        pattern=sheet_pattern,
        title=goal or "GOODRICH",
        color=color
    )

    if rendered_sheet:
        result += "\\n\\n<hr><h3>ผลลัพธ์จัดแผ่นออฟไลน์</h3>"
        result += f'<img src="{rendered_sheet["url"]}" style="width:100%;max-width:520px;border-radius:22px;margin:10px 0;border:1px solid #ff9f22;">'
        result += f'<p><b>ไฟล์ผลลัพธ์:</b> {rendered_sheet["url"]}</p>'

    result = result + preview_html'''

    if old in s:
        s = s.replace(old, new, 1)
    else:
        print("เตือน: ไม่เจอบรรทัด result = result + preview_html")

    old_save = '''        "product_file": product_file,
        "result": result,'''
    new_save = '''        "product_file": product_file,
        "rendered_sheet": rendered_sheet if 'rendered_sheet' in locals() else None,
        "result": result,'''

    if old_save in s:
        s = s.replace(old_save, new_save, 1)

    p.write_text(s, encoding="utf-8")
    print("เพิ่ม AI_ABILITY_OFFLINE_RENDERER_V1 แล้ว")

